# Generated by Django 5.0.6 on 2025-11-06 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='selling_price_ves',
            new_name='selling_price_local',
        ),
    ]
